NUS-CRISP/CRISP

.github/workflows/backend-ci.yml
.github/workflows/frontend-ci.yml
CONTRIBUTING.md
LICENSE
backend/package.json
multi-git-dashboard/package.json
pull_request_template.md

updates to ci/cd pipeline, adding of MIT license and pr template
- add prettier check script
- modify ci pipeline to use new script
- add mit license
- add pr template
NA
NA
Resolves #136 #141

Documentation & CI/CD

---

backend/controllers/projectManagementController.ts

Fix import bug

---

nginx/default.conf

Add nginx security headers

---

multi-git-dashboard/src/pages/api/auth/[...nextauth].ts

Fix nginx security headers

---

backend/jobs/githubJob.ts

Add pagination and fetch with exponential backoff to GitHub cron job.
Resolves #213

Add pagination to Octokit REST API calls

---

backend/jobs/githubJob.ts
backend/jobs/trofosJob.ts

Fix Trofos fetch job bug

---

backend/app.ts
backend/controllers/codeAnalysisController.ts
backend/jobs/codeAnalysisJob.ts
backend/routes/codeAnalysisRoutes.ts
backend/services/codeAnalysisService.ts
backend/test/controllers/codeAnalysisController.test.ts
backend/test/models/codeAnalysisData.test.ts
backend/test/services/codeAnalysisService.test.ts
backend/test/services/githubService.test.ts
multi-git-dashboard/package-lock.json
multi-git-dashboard/package.json
multi-git-dashboard/src/components/Navbar.tsx
multi-git-dashboard/src/components/code-analysis/CodeAnalysisAccordianItem.tsx
multi-git-dashboard/src/components/code-analysis/CodeAnalysisOverview.tsx
multi-git-dashboard/src/components/code-analysis/CodeAnalysisTimeline.tsx
multi-git-dashboard/src/components/views/CodeAnalysis.tsx
multi-git-dashboard/src/lib/utils.ts
multi-git-dashboard/src/pages/courses/[id]/code-analysis/index.tsx

Implement backend to handle API calls to get code analysis data, and frontend to call API.
- Added code analysis controller,service and routes.
- Added testing for code analysis controller, service and routes.
- Added code analysis tab on frontend and call API.
- Fixed error in githubService test.
- Added Overview and Timeline views for code analysis
- Fixed bugs for code analysis job:
- Allow pull / clone of private repos
- Mkdir for repos before cloning
Resolves #199 ,  #222 , #233 , #234 , #240, #241

Code analysis backend and frontend

---

backend/services/codeAnalysisService.ts
backend/test/controllers/codeAnalysisController.test.ts
backend/test/services/codeAnalysisService.test.ts

Added testing for uncovered lines in code analysis service and controller.
Resolves #244

Added test for code analysis

---

backend/app.ts

fix import errors

---

multi-git-dashboard/src/components/cards/SubmissionCard.tsx
multi-git-dashboard/src/components/views/AssessmentInternalForm.tsx
multi-git-dashboard/src/pages/courses/[id]/internal-assessments/[assessmentId]/take.tsx

Fix Saving Submission Deaft

---

backend/services/submissionService.ts
backend/test/services/submissionService.test.ts
multi-git-dashboard/src/components/views/AssessmentInternalForm.tsx

Lock Ordering for Released Assessments and Skip Regrading Soft Deleted Submissions

---

multi-git-dashboard/src/components/views/AssessmentInternalForm.tsx
multi-git-dashboard/src/pages/courses/[id]/internal-assessments/[assessmentId]/take.tsx

Temporarily disable this feature so that the other contributors can first deploy current version of CRISP to prod. Save draft doesn't work right now.

Disable Draft Feature

---

backend/routes/internalAssessmentRoutes.ts
multi-git-dashboard/src/components/views/AssessmentInternalForm.tsx

Second attempt at fixing recall/release not updating page bug

Change Recall and Release Request Types to PATCH

---

backend/controllers/internalAssessmentController.ts

Fourth attempt at fixing recall/release not updating page bug

Add await to .save call

---

backend/controllers/internalAssessmentController.ts
backend/test/controllers/internalAssessmentController.test.ts
multi-git-dashboard/src/components/cards/AssessmentMakeQuestionCardComponents/Edit/ScaleQuestionEdit.tsx
multi-git-dashboard/src/components/cards/AssessmentMakeQuestionCardComponents/View/ScaleQuestionView.tsx
multi-git-dashboard/src/components/forms/CreateInternalAssessmentForm.tsx
multi-git-dashboard/src/components/views/AssessmentInternalForm.tsx
multi-git-dashboard/src/components/views/AssessmentInternalOverview.tsx
multi-git-dashboard/src/pages/courses/[id]/internal-assessments/[assessmentId].tsx
multi-git-dashboard/src/pages/courses/[id]/internal-assessments/[assessmentId]/take.tsx

Fix bug in Scale Question Card View/Edit Preview. 
Add alert calls to errors in assessment framework

Fix Scale Label Formatting and Add Alerts in Error Handling

---

backend/jobs/codeAnalysisJob.ts

Fix bug of Sonar API returning undefined for metric values. 3 attempts with 90s delay for API.
Resolves #266

bug fixes for code analysis: sonar api issues

---

backend/jobs/codeAnalysisJob.ts
multi-git-dashboard/src/components/code-analysis/CodeAnalysisOverview.tsx
multi-git-dashboard/src/components/code-analysis/CodeAnalysisTimeline.tsx
multi-git-dashboard/src/lib/utils.ts

Added composite metrics, with mean and median.
Added help icon to hover over for metric meanings rather than over titles.
Added icon to hover over on overview for mean and median rather than over values.
- Code analysis job to check for composite metrics
- Help icon with title
- Mean median icon with values
- Composite metrics in overview and timeline
Resolves #270 #269

Composite metrics

---

backend/package.json
multi-git-dashboard/package.json

Add bcrypt and sharp build dependencies due to breaking pnpm update

update pnpm built dependencies

---

docker-compose.yml

add backend dependency on mongo

---

docker-compose.yml

add additional checks for backend-mongo

---

docker-compose.yml

Revert "add additional checks for backend-mongo"

---

multi-git-dashboard/src/components/forms/ConnectTrofosForm.tsx
multi-git-dashboard/src/components/forms/CreateCourseForm.tsx
multi-git-dashboard/src/components/forms/MilestoneForm.tsx
multi-git-dashboard/src/components/forms/SprintForm.tsx
multi-git-dashboard/src/pages/auth/register.tsx

add types for validate

---

backend/app.ts
backend/jobs/tutorialDataJob.ts
backend/services/courseService.ts
multi-git-dashboard/src/components/Navbar.tsx
multi-git-dashboard/src/components/views/Overview.tsx

Fixes issues of broken stages 1 and 6 tutorial popovers. The cause for stage 1 is that the box appears below the sticky navbar due to TutorialPopover's default behavior of being below the tutorial item. The cause of stage 6 is due to magic strings where the tab state changes to "Class Overview" but stage 6 popover expects "Overview" from older code.
Resolves #298

Fix Broken Tutorial Popover

---

backend/controllers/notificationController.ts
backend/test/controllers/accountController.test.ts
multi-git-dashboard/src/components/forms/NotificationSettingsForm.tsx
multi-git-dashboard/src/pages/courses/index.tsx

Moves button to send test email to the notification settings modal. Also added a button to send test telegram message notification. Also made the test notification button more flexible in its use cases.

Move Test Email to Notification Settings Modal

---

devops/docker-compose.yml

Sonarqube-8000-migration

---

backend/jobs/tutorialDataJob.ts

Add Mock proj management and code analysis data

---

backend/jobs/tutorialDataJob.ts

Just added more teams into the tutorial trial data.

Add More Trial Teams

---

backend/jobs/notificationJob.ts

Moved greeting lines and closing lines of notifications to before and after gathering of each notification.  Also, added comments on how to add onto the notification job file.

Move Greetings and Closing of Notifications

---

backend/clients/notificationFacadeClient.ts

Added method to check if user wants notifications.

Add Method to Check if User Wants Notifications

---

backend/jobs/tutorialDataJob.ts
backend/services/courseService.ts
backend/test/services/courseService.test.ts

Fix the case-sensitivity of name and email

Fix-student-name

---

multi-git-dashboard/src/components/overview/analytics/team/WeeklyContributions.tsx

Fix error on reading undefined in weeklycontributions

add check for weeklyCommits

---

backend/jobs/aiInsightsJob.ts

Send notifications to faculty and TAs for the course (if notification is turned on). Will be sent upon every time ai insights is generated. (So frequency of notification depends on frequency of ai insights generation specified by the course coordinator).

AI Insights Notification

---

backend/jobs/githubJob.ts
backend/jobs/publicGithubJob.ts

fix: Job issue

---

backend/jobs/githubJob.ts
backend/jobs/publicGithubJob.ts

fix: eslint

---

backend/services/courseService.ts
backend/test/services/courseService.test.ts

In order to ensure admin gets faculty access to all future courses, we auto-add admin upon course creation. We also remove hide admin from being retrieved in the get people from course method for aesthetic purposes.

Auto add admin into courses

---

backend/test/services/courseService.test.ts

Add Course Service Sorting to test

---

backend/test/services/courseService.test.ts

update getpeopleformcourse message

---

backend/services/courseService.ts
backend/test/services/courseService.test.ts

add ignore sorting

---

backend/jobs/aiInsightsJob.ts
backend/jobs/codeAnalysisJob.ts
backend/jobs/githubJob.ts
backend/jobs/jiraJob.ts
backend/jobs/publicGithubJob.ts
backend/jobs/trofosJob.ts
backend/jobs/tutorialDataJob.ts
backend/utils/overviewMetrics.ts
multi-git-dashboard/package-lock.json
multi-git-dashboard/package.json
multi-git-dashboard/src/components/code-analysis/CodeAnalysisOverview.tsx
multi-git-dashboard/src/lib/utils.ts

Added method to get weighted sum and rank in code analysis job. Edited frontend to display ranks. Also added checks to all jobs that query course to run only for ongoing courses.
- Code Analysis Job new methods:
- Get teamIds belonging to course
- Get latest code analysis data belonging to teamId
- Get relevant code metrics and normalise
- Calculate weighted sum
- Calculate Rank
- Write into metrics, values, types and domains (New metrics 'overview_rank' and 'overview_score', new domain 'Overview')
- Frontend now displays rank at the top of the overview. Score is not shown anywhere. Timeline does not show rank or score.

Add weighted sum and rank

---

backend/controllers/accountController.ts
backend/controllers/assessmentAssignmentSetController.ts
backend/controllers/assessmentResultController.ts
backend/controllers/courseController.ts
backend/controllers/internalAssessmentController.ts
backend/controllers/submissionController.ts
backend/controllers/userController.ts
backend/services/submissionService.ts
backend/test/controllers/assessmentAssignmentSetController.test.ts
backend/test/controllers/assessmentResultController.test.ts
backend/test/controllers/internalAssessmentController.test.ts
backend/test/controllers/submissionController.test.ts
backend/test/controllers/teamSetController.test.ts

Because Vercel decided to over-cache everything

Add No-Cache Headers

---

backend/services/submissionService.ts

Because I was working on this bit of code at 3am a few days ago

Fix Incorrect Similarity Check

---

backend/controllers/internalAssessmentController.ts
backend/services/googleService.ts
backend/services/submissionService.ts
backend/test/controllers/internalAssessmentController.test.ts
backend/test/services/googleService.test.ts

Also add code coverage for prod deployment

Fix Async Issue

---

backend/services/submissionService.ts
backend/test/services/submissionService.test.ts
multi-git-dashboard/src/components/cards/SubmissionCard.tsx
multi-git-dashboard/src/components/views/AssessmentInternalOverview.tsx

Simply removes a guard statement and associated test. Also changes a frontend component to reflect the granularity of the assessment.

Remove Restriction on Multi-Submissions for Individuals

---

backend/Dockerfile
multi-git-dashboard/Dockerfile

specify timezone for docker

---

backend/Dockerfile

update maven url

---

mongo/Dockerfile

downgrade mongo for compatability
